image: gradle:alpine

variables:
  GRADLE_OPTS: ""

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew compileJava
    - ls -al
    - echo "------------------"
    - ls -al build
    - echo "------------------"
    - ls -al src