image: gradle:alpine

variables:
  GRADLE_OPTS: ""


before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

stages:
  - build
  - test
  - release

build:
  stage: build
  script:
    - ./gradlew jar
  artifacts:
    paths:
    - build/libs/fuzzdbunit*.jar
    expire_in: 2 hours

test:
  stage: test
  script:
    - ./gradlew test

release:
  stage: release
  script:
    - ./gradlew release
    - git commit -m "Update version"
    - git push