image: gradle:alpine

variables:
  GRADLE_OPTS: ""

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew jar
    - ls -al build
    - echo "***********************"
    - ls -al build/libs
  artifacts:
    paths:
    - build/libs/fuzzdbunit-0.1-SNAPSHOT.jar
    expire_in: 2 hours